### ISSUE TITLE
gfx1151 suffers from GPU hangs

### ISSUE THREAD

**Issue by Mushoz** [lemonade-sdk/llamacpp-rocm#11]
There are many reports of GPU hangs with gfx1151 under ROCm, which I also experience running llamacpp-rocm from this repo, eg:

https://gitlab.freedesktop.org/drm/amd/-/issues/4321
https://github.com/ROCm/ROCm/issues/5151
https://github.com/ROCm/rocm-libraries/issues/1132

In that first link, Mario Limonciello investigated the issue internally and found that a fix has already been created back in July. His comment stating that can be found here: https://gitlab.freedesktop.org/drm/amd/-/issues/4321#note_3045126

Mario also mentioned in the following comment: https://gitlab.freedesktop.org/drm/amd/-/issues/4321#note_3048205
That this fix is not yet backported to any release branch, including ROCm 7. Furthermore, it will not be included in the initial ROCm 7 release, but will actually hit ROCm in a later point release.

In my opinion leaving such a critical bug unfixed for so long is unacceptable. Since this llamacpp build specifically targets gfx1151, I was wondering if you could bring this issue up internally and push for an earlier fix than a ROCm 7 point release. Gfx1151 has been marketed and sold with a big focus on AI, but the AI experience right now is terrible due to this bug. Thank you!

**Comment by danielholanda** [comment]
Hi @Mushoz,

Attempting to reproduce this ended up being incredibly painful given the size of the model as I kept getting "failed to load model". That said, I was able to make some good progress on this.

**The good news** is that I found a bug where a stray "ad-hoc" build of TheRock was being picked up by the build system of this repo. As a result, we were using older versions of TheRock than we should. This was fixed [here](https://github.com/lemonade-sdk/llamacpp-rocm/pull/16). All builds from b1050 onwards have this fix. Please try it out and let me know if this fixes your issue.

If b1050 doesn't fix this issue for you, you can at least now rest assured that the automatic releases we are generating here will include the fix as soon as the fix is included in TheRock. If your issue is not fixed, please open an issue on TheRock and let me know, so I can point it to them and ping the right people internally.

**Comment by Mushoz** [comment]
I replaced the `wget` line in my dockerfile with `https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1053/llama-b1053-ubuntu-rocm-gfx1151-x64.zip` but the same issue persists. I will open a new issue on TheRock and link back to here. Hopefully someone can help us out!

**Comment by Mushoz** [comment]
@danielholanda , Created an issue in the TheRock repo here: https://github.com/ROCm/TheRock/issues/1413

**Comment by ianbmacdonald** [comment]
I was unable to reproduce this [on 7.0rc1 from packages](https://netstatz.com/strix_halo_lemonade/) with b1057 that ships with lemonade v8.1.10 running with 122880M of GTT memory. 

```
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$ ./llama-bench -m /mnt/models/huggingface/hub/models--unsloth--GLM-4.5-Air-GGUF/snapshots/a5133889a6e29d42a1e71784b2ae8514fb28156f/UD-Q4_K_XL/GLM-4.5-Air-UD-Q4_K_XL-00001-of-00002.gguf -fa 1 -r 5 --mmap 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | ---: | --------------: | -------------------: |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           pp512 |         89.96 ± 0.47 |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           tg128 |         19.43 ± 0.02 |

build: 4f63cd70 (6431)
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$ ./llama-bench -m /mnt/models/huggingface/hub/models--unsloth--GLM-4.5-Air-GGUF/snapshots/a5133889a6e29d42a1e71784b2ae8514fb28156f/UD-Q4_K_XL/GLM-4.5-Air-UD-Q4_K_XL-00001-of-00002.gguf -fa 1 -r 5 --mmap 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | ---: | --------------: | -------------------: |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           pp512 |         90.51 ± 0.36 |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           tg128 |         19.42 ± 0.06 |

build: 4f63cd70 (6431)
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$ ./llama-bench -m /mnt/models/huggingface/hub/models--unsloth--GLM-4.5-Air-GGUF/snapshots/a5133889a6e29d42a1e71784b2ae8514fb28156f/UD-Q4_K_XL/GLM-4.5-Air-UD-Q4_K_XL-00001-of-00002.gguf -fa 1 -r 5 --mmap 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | ---: | --------------: | -------------------: |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           pp512 |         91.74 ± 0.44 |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           tg128 |         19.45 ± 0.01 |

build: 4f63cd70 (6431)
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$ ./llama-bench -m /mnt/models/huggingface/hub/models--unsloth--GLM-4.5-Air-GGUF/snapshots/a5133889a6e29d42a1e71784b2ae8514fb28156f/UD-Q4_K_XL/GLM-4.5-Air-UD-Q4_K_XL-00001-of-00002.gguf -fa 1 -r 5 --mmap 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | ---: | --------------: | -------------------: |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           pp512 |         89.45 ± 0.38 |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           tg128 |         19.48 ± 0.01 |

build: 4f63cd70 (6431)
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$ ./llama-bench -m /mnt/models/huggingface/hub/models--unsloth--GLM-4.5-Air-GGUF/snapshots/a5133889a6e29d42a1e71784b2ae8514fb28156f/UD-Q4_K_XL/GLM-4.5-Air-UD-Q4_K_XL-00001-of-00002.gguf -fa 1 -r 5 --mmap 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | ---: | --------------: | -------------------: |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           pp512 |         90.13 ± 0.43 |
| glm4moe 106B.A12B Q4_K - Medium |  68.01 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           tg128 |         19.46 ± 0.03 |

build: 4f63cd70 (6431)
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$
```
I stepped it up to 6bit XL to push over the 96GB line (GTT Total Used Memory (B): 97884790784) and was still unable to reproduce.
```
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$ ./llama-bench -m /mnt/models/huggingface/hub/models--unsloth--GLM-4.5-Air-GGUF/snapshots/a5133889a6e29d42a1e71784b2ae8514fb28156f/UD-Q6_K_XL/GLM-4.5-Air-UD-Q6_K_XL-00001-of-00003.gguf -fa 1 -r 5 --mmap 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | ---: | --------------: | -------------------: |
| glm4moe 106B.A12B Q6_K         |  94.57 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           pp512 |         89.39 ± 0.39 |
| glm4moe 106B.A12B Q6_K         |  94.57 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           tg128 |         15.73 ± 0.00 |

build: 4f63cd70 (6431)
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$ ./llama-bench -m /mnt/models/huggingface/hub/models--unsloth--GLM-4.5-Air-GGUF/snapshots/a5133889a6e29d42a1e71784b2ae8514fb28156f/UD-Q6_K_XL/GLM-4.5-Air-UD-Q6_K_XL-00001-of-00003.gguf -fa 1 -r 5 --mmap 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
| model                          |       size |     params | backend    | ngl | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | ---: | --------------: | -------------------: |
| glm4moe 106B.A12B Q6_K         |  94.57 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           pp512 |         95.41 ± 0.46 |
| glm4moe 106B.A12B Q6_K         |  94.57 GiB |   110.47 B | ROCm       |  99 |  1 |    0 |           tg128 |         15.70 ± 0.01 |

build: 4f63cd70 (6431)
(lemonade) imac@ai2:~/src/lemonade/.venv/bin/rocm/llama_server$
```

**Comment by Mushoz** [comment]
I am not sure exactly what fixed it, but I am now no longer getting any crashes with llamacpp-rocm from the lemonade-sdk. I am also using the latest linux-firmware-git installed through the aur. I will close the issue for now. Should I run into additional issues I will reopen it. Thanks for the fixes!
